### ISSUE TITLE
Mod 加载器识别错误

### ISSUE THREAD

**Issue by hejiehao** [Coloryr/ColorMC#10]
### 问题描述
![image](https://github.com/Coloryr/ColorMC/assets/98140773/96f54831-198e-4545-bfc7-f620c720851e)
[I18nUpdateMod-3.5.0-all.jar](https://mediafilez.forgecdn.net/files/4611/692/I18nUpdateMod-3.5.0-all.jar)
该 Mod 是双端支持的，而启动器将它识别成 Fabric

### 解决方案
通过 hash 来获取这个 Mod 所支持的 Mod 加载器

**Comment by Coloryr** [comment]
这个是forge core mod + fabric mod，forge core mod不能完整识别

**Comment by hejiehao** [comment]
> 这个是forge core mod + fabric mod，forge core mod不能完整识别

为何不通过 API 来识别呢？
