### ISSUE TITLE
整合包导出

### ISSUE THREAD

**Issue by Sz-Yuan** [Coloryr/ColorMC#13]
能否添加mcbbs格式整合包导出，modrinth和curseforge格式整合包导出感觉并不完善  
![image](https://github.com/Coloryr/ColorMC/assets/143470829/6a9280ef-5bbe-498e-8195-91c6dd17e625)  
是否能完善modrinth和curseforge格式整合包导出，实现自定义选择配置文件和其他文件，就像mulitmc导出modrinth整合包和curseforge导出整合包格式一样  
这些只是我的一些看法

**Comment by Coloryr** [comment]
自定义选择配置文件和mod下载都有选择，你点左上角那个蓝色按钮就懂了，MCBBS整合包不打算添加支持

**Comment by Coloryr** [comment]
还有目前最新版是A21，A20已经不再更新

**Comment by Sz-Yuan** [comment]
> 自定义选择配置文件和mod下载都有选择，你点左上角那个蓝色按钮就懂了，MCBBS整合包不打算添加支持

原来如此，是我粗心大意了🐔，原谅我在问一句，A21版本在哪里能找到

**Comment by Coloryr** [comment]
在群里

**Comment by Coloryr** [comment]
没其他问题就把这个关了
