### ISSUE TITLE
反复修改下载线程数会造成较高的 CPU 负担

### ISSUE THREAD

**Issue by Myitian** [Coloryr/ColorMC#16]
### 问题
反复修改下载线程数会大量销毁和创建线程，造成较高的 CPU 负担；如果不小心填入了特别大的值（比如 10000 ），会使程序卡顿或假死，且由于保存进了配置文件，重新启动程序仍会卡顿或假死
### 建议
- 等修改完成后再调整线程数；
- 加入上限；
- 当用户尝试设置一个特别大的值时，发出警告让用户二次确认；
- 仅销毁/创建与原先线程数量之差
### 截图
![界面](https://github.com/Coloryr/ColorMC/assets/76843407/5bd3201a-375b-4736-8f17-4f531eb93165)
![性能监视](https://github.com/Coloryr/ColorMC/assets/76843407/daad61bd-334a-4fec-9a04-bcba75d6a63b)

**Comment by Coloryr** [comment]
改成修改线程数需要重启启动器了
