### ISSUE TITLE
How about creating a Fedora version (RPM)?

### ISSUE THREAD

**Issue by ssh1579** [Coloryr/ColorMC#21]
I'm a Fedora user and I don't want to install it using user install. 
我是一个Fedora用户，但我不想用Alien进行转换，也不想把启动器拷到~/.local/bin，还对直接用APT安装不太放心，创建Debian/Arch子系统也不是我喜欢的方法，我还不喜欢用Toolbx/Distrobox，虚拟机会有性能损耗，我我也不想安装Ubuntu，因为它容易掉驱动，影响游戏体验，Arch的pacman又极度辣鸡，换成Manjaro又要忍受我无法忍受的半个月更新延迟，Debian连网卡驱动都没有，Windows下又有PCL，macOS我不用，我还不喜欢自己打代码编译，我还......
就算不搞rpm至少也得搞个snap/flatpak版吧，我还用solusopensusemageiapclinuxosvoidendlessgnomeoscentosrhelrisiosalpinefreebsdnixosguix
搞不懂？
> Solus
> openSUSE
> Mageia
> PCLinuxOS
> Void
> Endless
> GNOME OS
> CentOS
> RHEL
> risiOS
> Alpine
> FreeBSD
> NixOS
> Guix
> ……

 
 
 
\
\
\
\
\
\
\
\
\
\
\----------

 
 
 
 
 

~~额……其实Fedora用户大都Linux技术较高（比如我）
（废话）
对不起，中二病犯了（其实我就初中二年级）~~

**Comment by ssh1579** [comment]
再顺便喷一下mojang吧，这货也不提供Fedora版
有趣的是，Java只提供RPM包，由此可见mojang作死的决心
尽然还有一大批人在效仿

> # **_~`FUCK YOU`~_**
> ~`#00ff00` ***你绿了***~

**Comment by ssh1579** [comment]
改编自Linus Torvalds的一句话：

> _NVIDIA, Fuck you!  --Linus Torvalds_
（想当年英伟达就是因为显卡不支持Linux才被喷的）

**_Mojang, Fuck you!_** _--Shihao S_
（气死我了，MC竟然没有Fedora包）

**Comment by ssh1579** [comment]
~注意，我是喷子~

**Comment by Coloryr** [comment]
6，你连appimage是啥都不懂吗

**Comment by ssh1579** [comment]
不是……你在ubuntu里构建rpm是个什么意思

**Comment by Coloryr** [comment]
https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
了解一下

**Comment by ssh1579** [comment]
建立fedora-rawhide:latest的docker/podman

微调rpm构建脚本，主要为删除涉及apt的命令:

```bash
sudo apt install rpm
```

并改为

```bash
sudo dnf in rpm-build
```

稍微对上述脚本进行修改，增加`dnf`/`zypper`/`apt`(apt-rpm)/`urpmi`/`yum`的检测

---------

更一劳永逸的方法是构建flatpak,并在flathub上发布

**Comment by Coloryr** [comment]
难道ubuntu构建的rpm不能在redhead系的系统用？

**Comment by ssh1579** [comment]
刚换solus,想想还是flatpak好
要不我自己搞
