### ISSUE TITLE
添加游戏实例卡主

### ISSUE THREAD

**Issue by Yamds** [Coloryr/ColorMC#22]
![bc5afbe8700b8d1852d2dc21fbe2229e](https://github.com/user-attachments/assets/972d29ad-c6e5-4c31-9ef1-87ad2077fc67)
![506d1130ae05fd5becf189ed88cc8788](https://github.com/user-attachments/assets/9b5ca0a8-81d1-4f2c-8112-a3ec643e3b90)
![图片](https://github.com/user-attachments/assets/7b5d4442-9e1a-4627-9ea0-29534ac4b623)
![recording](https://github.com/user-attachments/assets/fb261a72-e425-4c0f-bb8e-17b6cb03b948)

添加游戏实例会被资源包里个别图片卡主orz，而且只会在这几个图片卡主，没找到什么共同点

**Comment by Coloryr** [comment]
发个样例给我看看

**Comment by Yamds** [comment]
https://wwo.lanzouq.com/ifsGu26sgnsj
里面就一个材质包，包含那个导入不进来的图

**Comment by Coloryr** [comment]
我选的直接解压一下子就导入就去了

**Comment by Yamds** [comment]
嘶不会是系统或者什么玄学问题吧，我这导入就像上面那个gif所示一样，每次都会卡住，别的端也一样

**Comment by Coloryr** [comment]
看看log里面有没有报错

**Comment by Yamds** [comment]
看log找到问题了，说文件没法访问，打开看发现那个别图片是只读模式...按理说只读应该也能访问或者黏贴之类操作来着
![图片](https://github.com/user-attachments/assets/fdd524c3-319d-442d-b640-b2502016e369)
