### ISSUE TITLE
ASM在启动时产生冲突

### ISSUE THREAD

**Issue by MorningMC** [Coloryr/ColorMC#23]
当我启动一个Minecraft实例时,总会报错
![image](https://github.com/user-attachments/assets/d254bc98-a47e-4c8d-914c-3bac6a102fa4)
经过调查,启动器在启动时会同时下载9.3和9.7.1的asm,两者包含相同的文件导致jvm报错
日志中包含`ColorMC ASM start`,推测是启动器的问题?

**Comment by MorningMC** [comment]
测试了一下,官启启动同一个实例不会冲突

**Comment by Coloryr** [comment]
你这启动的啥版本

**Comment by Coloryr** [comment]
我懂了 1.21.3更换了asm版本，但是fabric没换
