### ISSUE TITLE
启动器内链接指向不存在的页面

### ISSUE THREAD

**Issue by Myitian** [Coloryr/ColorMC#7]
启动器设置 -> 关于 下的“用户手册”和“MC百科”指向以下链接
https://github.com/Coloryr/ColorMC/blob/master/guide/Main.md
但该链接指向的文件不存在
![Screenshot 2023-09-27 at 22-39-29 File not found · Coloryr_ColorMC](https://github.com/Coloryr/ColorMC/assets/76843407/b8ba73fd-6974-4ed1-869d-a529bf21fd21)

**Comment by Coloryr** [comment]
fix in 9631270f897d559fd36826e4dbd15c1a610830a2
