### ISSUE TITLE
在数字输入框输入无法解析的内容，异常提示会干扰布局

### ISSUE THREAD

**Issue by Myitian** [Coloryr/ColorMC#8]
在数字输入框输入无法解析的内容，异常提示会干扰布局
<img src="https://github.com/Coloryr/ColorMC/assets/76843407/09e258c9-6077-4f53-9e55-c990e5135228" width="678" />
<img src="https://github.com/Coloryr/ColorMC/assets/76843407/f770892f-f5dd-4c96-b55a-3a6d852c3b83" width="666" />

**Comment by Coloryr** [comment]
还有其他地方吗
